#!/bin/sh
#
# Copyright 2015 Nexenta Systems, Inc. All rights reserved.

TERM=sun-color
USER=root
HOME=/root
PATH=/sbin:/usr/sbin:/usr/bin
TERMINFO=/usr/share/lib/terminfo
EDITOR=vi
SHELL=bash
PAGER='/usr/bin/less -ins'
PS1="\e[0;32m\u@\h# \e[m"

export TERM USER HOME PATH TERMINFO EDITOR SHELL PAGER PS1

/usr/sbin/checkrpool

/sbin/sulogin
